### ISSUE TITLE
Standard Life Itself video opening and closing frames

### ISSUE THREAD

**Issue by theo-cox** [life-itself/comms#16]
Rufus suggested for our videos that we use the thumbnail as an opening frame before the video starts, and create a standard closing image we display at the end for a few seconds giving info like our website.

If you agree this is a good idea, then could you quickly do the closing image in Canva in the same style as the thumbnail/opener?

## Acceptance
- [x] Standard closing frame image made and saved in Gdrive
- [x] Instructions added to SOP
- [x] [Optional - to your discretion @nathenf] - Key videos updated with opener and closer

**Comment by nathenf** [comment]
@theo-cox this is not something I can simply add in Youtube, but would have to download the full video, cut it together, export it, and upload again. This is quite a long process so I think the time outweighs the value of adding it on. I also found out that Kapwing has a 1 hour length limit for exports which means it is not so useful for our Youtube videos since they are all over 1 hour long. 

I'm trying to update my laptop to get video editing software... Let's see. I would still prefer Kapwing for reels.

**Comment by nathenf** [comment]
Actually Canva can work quite well for this, I've done it for the Web3 one now

**Comment by nathenf** [comment]
Update for this, actually Canva did not work. Everything was going great but when it came to downloading the file Canva can't handle it. Seems web editors can only handle under 1 hour. 

I am looking to download Da Vinci Resolve, but the power of my laptop is not ideal for such editing program

**Comment by theo-cox** [comment]
I'd say if its hugely laborious let's not bother. We can add end screens via YT studio which is a good, low cost way to start IMO

**Comment by nathenf** [comment]
I agree, I'll keep searching for a solution though, but in the meantime keep it to a minimum

**Comment by nathenf** [comment]
Fixed - Overlays for call to action and end screen made and added to Gdrive
Not Fixed - Need a better computer (and video editing software) to edit the videos effectively. Potentially something we could outsource to a video editor here is Bali it would take them very little time to do. However, not a priority lets focus on making better content first.
