### ISSUE TITLE
Nonporift Canva

### ISSUE THREAD

**Issue by theo-cox** [life-itself/comms#38]
Life Itself CIC: https://find-and-update.company-information.service.gov.uk/company/12111144
Charity Registration Number from Charity Commission, CIC Registration Number from CIC Regulator, Articles and Memorandum of Association

https://www.canva.com/help/article/canva-for-nonprofits/ 

## Acceptance

- [x] We have applied for a nonprofit Canva account ✅  **Applied. Should hear back in 7-10 days**
- [ ] We have followed up with Canva around our rejection and made the case that we qualify

**Comment by theo-cox** [comment]
@EilidhRoss1 see here for issue re nonprofit canva. would say medium priority as we just need to get it done before we get charged when our free trial ends

**Comment by EilidhRoss1** [comment]
Have got in touch for further guidance on why we did not meet their eligibility criteria and asking to know if there's any further documentation they need. Have had another look at their eligibility criteria and I'm thinking the reason we might have been declined is because we need to demonstrate that we are not making a profit. [See the screenshot here](https://drive.google.com/file/d/1ek9qbQCFVRQ0Kwp4XNOysrlzVqEcHecQ/view?usp=sharing). @theo-cox do you know where I could find any evidence demonstrating that our mission is not to gain any profit, and/or any documentation that shows that the majority of any profit we might make is reinvested into achieving our mission?

**Comment by theo-cox** [comment]
FIXED. Our application has since been approved.
